### ISSUE TITLE
Robot rotates around a point instead of rotating around itself

### ISSUE THREAD

**Issue by vatanaksoytezer** [frc-web-components/frc-web-components#16]
Hello @amorygalili ,

Thank you for your great work and releasing this great tool to community as open source. We've been experimenting with web-components for a day or two and realized that the robot in the field example ([https://frc-web-components.github.io/examples/vanilla/field/field.html](https://frc-web-components.github.io/examples/vanilla/field/field.html)) does not rotate around itself, rather it rotates around a fixed point. While doing so robot looks like it is also changing it's X and Y position visually (although x and y values are fine). 

I would have liked to fix it but I have absolutely no idea about web programming (in fact it is the first time I am looking at a html/css/js code). But my guesses are it is related with it's transform origin being center top in the snippet below. Though I could not find anything related in your source code.

`<frc-field-object source-key="/robot" source-provider="NetworkTables" x="8.00000000000001" y="7" rotation="-7.016709298534876e-15" width="2" height="3" image="" unit="ft" style="width: 15.2563px; height: 22.8844px; transform-origin: center top; transform: translate(45.7688px, 61.025px) rotate(90deg);">
    <frc-field-robot source-provider="NetworkTables" draw="function anonymous(
) {
()=>{}
}" unit="" color="blue"></frc-field-robot>
</frc-field-object>`

Thanks,
Vatan

**Comment by amorygalili4** [comment]
Hi @vatanaksoytezer thanks for the feedback! I thought this made sense to do, since at least when my team tracked our robot's position and followed trajectories we usually referred to the front of the robot as the origin. Now that I think about it this probably doesn't make sense, and actually is completely unnecessary since you can get the same effect by making the robot a child of another field object with an offset. I believe I will have time to fix this issue sometime tomorrow.

**Comment by amorygalili** [comment]
Hi @vatanaksoytezer thanks for the feedback! I thought this made sense to do, since at least when my team tracked our robot's position and followed trajectories we usually referred to the front of the robot as the origin. Now that I think about it this probably doesn't make sense, and actually is completely unnecessary since you can get the same effect by making the robot a child of another field object with an offset. I believe I will have time to fix this issue sometime tomorrow.

**Comment by amorygalili** [comment]
@vatanaksoytezer I updated the example and added a new release with the bug fix. Let me know if it behaves the way you expect and I'll close the issue.

**Comment by vatanaksoytezer** [comment]
Hello @amorygalili ,

Thank you very much for taking this into account. We tried the new example and it seems exactly what we were looking for.

Also maybe a little bit unrelated with this issue (I can open a new one though) but is there anyway we can get the compile instructions (and your library setup) to compile our frc-web-components.js file? I tried something with babel but couldn't figure out (Sorry it is first time I am dealing with any js code).

Thanks a lot again, and have a nice day!

**Comment by amorygalili** [comment]
There's an npm package you can use. You can install with the following command:

`npm install --save @frc-web-components/frc-web-components`

You can either then include the file as a script from your node modules folder in your HTML file:

`<script src="./node_modules/@frc-web-components/frc-web-components/build/frc-web-components.min.js"></script>`

Or include the module yourself if you want to build with babel + webpack. I added a couple examples you can download: https://github.com/frc-web-components/examples

To use either you must run `npm install` to install all the dependencies. For the babel/webpack example, you can run `npm start` to make the example compile and open up in the browser automatically. Webpack will watch for changes when you save and automatically reload the page with your latest build.

Let me know how this works out for you. Downloading the script from the releases page is probably the easiest way for someone without much experience with web technologies. Getting used to using tools such as babel and webpack is not always easy, which is why I haven't prioritized documenting this approach (although this is the preferred way since there are things you can do with babel/webpack that are not easy with vanilla javascript). I'll make adding additional documentation and example code a priority now that this approach has been requested.

**Comment by amorygalili** [comment]
I also just created a codesandbox if you want to try out the webpack example without downloading anything: https://codesandbox.io/s/github/frc-web-components/examples/tree/master/with-webpack

**Comment by vatanaksoytezer** [comment]
Thank you very much, will try with npm and let you know. Probably it will be best to close this issue, but I will make sure to PM you from chiefdelphi (or open up a new issue) when I try (probably in a few days or so). Thanks a lot for taking care of my comments this much.
