### ISSUE TITLE
3d-models not properly imported in react

### ISSUE THREAD

**Issue by HarlanHaller** [frc-web-components/frc-web-components#171]
I am working in the template react-custom-dashboard with my only changing being to add a Field3d with the following code

    <Field3d>
            <Field3dObject name="KitBot" translation={[0,0,0]} rotation={[0,0,0,0]} />
    </Field3d>

and including the imports for`Field3d` and `Field3dObject` from `@frc-web-components/react`.

However when I run this via `npm run dev` or `npm run build && npx http-server ./dist` I get 404 errors for the following files:

      /3d-models/Field3d_2024.glb
      /3d-models/Robot_KitBot.glb

I managed to find a workaround for this issue by copying the `3d-models` folder from `node_modules/@frc-web-components/fwc/dist/3d-models`  into my public folder.

I am very new to react so I have no idea how to fix this even after ~30 minutes of google searches. It is also very possible that there is an issue on my end.

Thank you for any help.

**Comment by amorygalili** [comment]
Not just on your end. This is very much an issue that I overlooked. The problem is that 3d models are so large adding them to each template (there are 6 templates currently) causes the published package size to exceed what's allowed in npm. Because of that I had to exclude them. I need to make it clear to teams that they have to download the assets themselves and place them in their public folder. I can add that warning in the README for now, but am open to other ideas.

Another possible solution: Display an error message in the Field3d component itself with a link to instructions on how to fix this problem if the model could not be loaded.

**Comment by HarlanHaller** [comment]
I think we can add a step to the end of the create cli that copies the files from node_modules to public. I forked to start making this change. Ideally there would be a way to rework the code to import them directly from the node_modules folder but I would not know how to do that.

I think adding the error message into the Field3d component would be a good measure regardless just in case something doesn't work

**Comment by amorygalili** [comment]
I'm not sure copying files from node_modules is the best solution long term. This currently works but the files bloat the `@frc-web-components/fwc` npm package, make installing it take a long time, and eventually it will become too large to publish when additional models are added. Perhaps we could copy files over, but maybe it could download it from somewhere else, like the fwc git repo?

**Comment by HarlanHaller** [comment]
I reworked my changes so that it was able to pull from a different github repo I created. So I can confirm that you could make a repo dedicated to the 3d models or all assets and then download and unzip those files into public. I will create a pull request draft to show what you what the code is. I will do it as a draft because it doesn't work for all templates and has hard-coded links to my temporary repos.

**Comment by amorygalili** [comment]
Awesome! Thanks for your work on this.
